global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ritbuddy'
    static_configs:
      - targets: ['localhost:8000']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
